### DISCUSSION TITLE
迁移数据表情包 class 属性问题

### DISCUSSION THREAD

**Discussion by inkss** [ArtalkJS/Artalk#126] [Q&A] [answered]
兼容迁移数据的表情包图片，例如 Twikoo 的 `tk-owo-emotion`，Waline 的 `vemoji` 等等。

https://github.com/ArtalkJS/Artalk/blob/35df0c14aec9b4d3d120408972b4d937c061a3eb/packages/artalk/src/lib/utils.ts#L203

**Comment by inkss** [comment]
我现在是用属性选择器判断的，效率低。

```css
.atk-content img[src*="emoji"] {
    height: 3em;
    vertical-align: middle;
}
```
