### DISCUSSION TITLE
前端配置项，放到后端配置文件，分页配置失效

### DISCUSSION THREAD

**Discussion by xiamuguizhi** [ArtalkJS/Artalk#135] [Q&A] [answered]
之前没怎么注意，今天才发现，我在后端 `conf.yml` 配置的 为 `autoLoad: false #(加载更多)`  没有起作用，还是 `拉倒底部就自动加载` ，不是需要点击 `加载更多`  的 加载

```
  pagination:
    pageSize: 15 #每页评论数
    readMore: true # 加载更多 or 分页条
    autoLoad: false # 自动加载 (加载更多)
```
