### DISCUSSION TITLE
error decoding 'Ports': Invalid hostPort: 端口号

### DISCUSSION THREAD

**Discussion by xiamuguizhi** [ArtalkJS/Artalk#238] [Q&A] [answered]
```bash

执行 ：  docker-compose up -d

# 报错

1 error(s) decoding:

* error decoding 'Ports': Invalid hostPort: 端口号
* 
```

版本 ： 

- Docker Compose version v2.4.1
- Docker version 20.10.17, build 100c701

**Comment by xiamuguizhi** [comment]
按照 `Docker Compose (推荐)`  安装，后面 `data目录`   也没有生成 数据库文件...

**Reply by qwqcode** [reply]
可以提供一下 `docker-compose.yml` 文件吗

**Reply by xiamuguizhi** [reply]
> 可以提供一下`docker-compose.yml`文件吗

我是复制官网的教程的 !

```
version: "3.5"
services:
  artalk:
    container_name: artalk
    image: artalk/artalk-go
    ports:
      - 端口号:23366
    volumes:
      - ./data:/data
```

因为Docker Compose 一直不成功，我现在换回了  Docker 了！
