### DISCUSSION TITLE
Need Help | 控制中心的弹窗与自定义 CSS 的冲突？

### DISCUSSION THREAD

**Discussion by Liynw** [ArtalkJS/Artalk#290] [Q&A] [answered]
Demo: https://oi.saiodgm.gq/bber/

我加了一段自定义 CSS 之后，Artalk 的右边出现了一个白色的框框，如图：

![image](https://user-images.githubusercontent.com/85772054/196016453-29547f9a-0440-43bb-990b-7004c9a94570.png)

我 F12 检查一下发现是这个元素：`atk-sidebar-iframe-wrap`。

导致出现这个问题的 CSS 语句是（一段加毛玻璃效果的 CSS）：

```css
#page{
    background-color: #fffd;
    backdrop-filter: blur(30px) saturate(180%);
    -webkit-backdrop-filter: blur(30px) saturate(180%);
}
```

我试着用 `not` 排除了一下，但是好像没用。

后面我又发现，只要把通知中心 / 控制中心点出来那个框就没了。

那么，这到底是 Artalk 的问题还是我 CSS 的问题还是什么别的问题？如何解决呢？
