### ISSUE TITLE
[Bug report | Artalk Go] Telegram 评论通知

### ISSUE THREAD

**Issue by leirock** [ArtalkJS/Artalk#152]
## 模板排版

默认的 Telegram 通知模板中（见上图），「来自 xxxx 的回复」这一行与评论内容之间并没有空行。

<img width="442" alt="image" src="https://user-images.githubusercontent.com/19180725/168928695-bd28db80-e3eb-4ee3-9a7c-29a907c61ce5.png">

**建议**：除了邮件提供自定义模板外，Telegram、钉钉等也提供用户自定义通知模板设置，方便用户自己修改。

## 重复通知

设置了邮件通知和 Telegram 通知后，收到评论会同时通过邮件和 Telegram 进行通知。

**建议**：提供一个管理员收取通知的渠道配置，例如：

```yaml
notify:
  # 管理员收取通知的方式
  admin:
    - email
    - telegram
    - dingtalk
```

```yaml
notify:
  # 管理员收取通知的方式
  admin:
    - telegram
    - dingtalk
```
