### ISSUE TITLE
待审核提示可以配置关闭吗？

### ISSUE THREAD

**Issue by rangujie** [ArtalkJS/Artalk#231]
<img width="545" alt="截屏2022-08-07 16 36 42" src="https://user-images.githubusercontent.com/17881618/183282559-26c2f905-f81c-4743-9698-bfcd1ead6014.png">
这个提示可改成配置显示或者关闭么

**Comment by qwqcode** [comment]
你可以用 CSS 隐藏这个提示

```css
.atk-comment .atk-pending {
    display: none !important;
}
```
