### ISSUE TITLE
Artalk error

### ISSUE THREAD

**Issue by sao-coding** [ArtalkJS/Artalk#265]
不知道為甚麼出現這個錯誤求解
![image](https://user-images.githubusercontent.com/58339015/191178457-83f27d26-2910-48d0-ba3c-bd3597116d99.png)

![image](https://user-images.githubusercontent.com/58339015/191178224-b650a9f8-c7d6-4a8f-84db-c796c9238871.png)
```yml
# HTTP Server
host: "0.0.0.0"

# 端口
port: 23366

# 加密密鑰
app_key: "C8763"

# 調試模式
debug: true

# 時區
timezone: "Asia/Taipei"

# 數據庫
db:
  type: "sqlite" # 支持 sqlite, mysql, pgsql, mssql
  file: "./data/artalk-go.db" # sqlite 數據庫文件
  name: "artalk"     # 數據庫名
  host: "localhost"  # 地址
  port: "3306"       # 端口
  user: "root"       # 賬號
  password: ""       # 密碼
  charset: "utf8mb4" # 編碼格式
  table_prefix: ""   # 表前綴 (例如："atk_")

# 日誌
log:
  enabled: true # 總開關
  filename: "./data/artalk-go.log" # 日誌文件路徑

# 緩存
cache:
  type: "builtin" # 支持 redis, memcache, builtin (自帶緩存)
  expires: 30     # 緩存過期時間 (單位：分鐘)
  warm_up: false  # 程序啟動時預熱緩存
  server: ""      # 連接緩存服務器 (例如："localhost:6379")

# 可信域名
trusted_domains:
  # - "*" # 無限制
  - "http://sao-x.com:23366"
  - "https://blog.sao-x.com"

# SSL
ssl:
  enabled: false
  cert_path: ""
  key_path: ""

# 默認站點名
site_default: "默認站點"

# 管理員賬戶
admin_users:
  - name: "only"
    email: "only@sao-x.com"
    password: "" # 密碼支持 bcrypt 或 md5 加密，例如填寫："(md5)50c21190c6e4e5418c6a90d2b5031119"
    badge_name: "管理員"
    badge_color: "#FF6C00"

# 登錄超時 (單位：秒)
login_timeout: 259200

# 評論審核
moderator:
  pending_default: false # 發表新評論默認為 “待審狀態”
  api_fail_block: false  # 垃圾檢測 API 請求錯誤仍然攔截
  # akismet.com 反垃圾
  akismet_key: ""
  # 騰訊雲文本內容安全 (tms)
  tencent: # https://cloud.tencent.com/document/product/1124/64508
    enabled: false
    secret_id: ""
    secret_key: ""
    region: "ap-guangzhou"
  # 阿里雲內容安全
  aliyun: # https://help.aliyun.com/document_detail/28417.html
    enabled: false
    access_key_id: ""
    access_key_secret: ""
    region: "cn-shanghai"
  # 關鍵詞詞庫過濾
  keywords:
    enabled: false
    pending: false # 匹配成功設為待審狀態
    files:         # 支持多個詞庫文件
      - "./data/詞庫_1.txt"
    file_sep: "\n" # 詞庫文件內容分割符
    replac_to: "x" # 替換字符

# 驗證碼
captcha:
  enabled: true    # 總開關
  always: false    # 總是需要驗證碼
  action_limit: 3  # 激活驗證碼所需操作次數
  action_reset: 60 # 重置操作計數器超時 (單位：s, 設為 -1 不重置)
  # Geetest 極驗
  geetest: # https://www.geetest.com
    enabled: false
    captcha_id: ""
    captcha_key: ""

# 郵件通知
email:
  enabled: false    # 總開關
  send_type: "smtp" # 發送方式 [smtp, ali_dm, sendmail]
  send_name: "{{reply_nick}}"      # 發信人昵稱
  send_addr: "noreply@example.com" # 發信人地址
  mail_subject: "[{{site_name}}] 您收到了來自 @{{reply_nick}} 的回覆"
  mail_tpl: "default" # 郵件模板文件
  smtp:
    host: "smtp.qq.com"
    port: 587
    username: "example@qq.com"
    password: ""
  ali_dm: # https://help.aliyun.com/document_detail/29444.html
    access_key_id: ""     # 阿里雲頒發給用戶的訪問服務所用的密鑰 ID
    access_key_secret: "" # 用於加密的密鑰
    account_name: "noreply@example.com" # 管理控制檯中配置的發信地址

# 圖片上傳
img_upload:
  enabled: true              # 總開關
  path: "./data/artalk-img/" # 圖片存放路徑
  max_size: 5                # 圖片大小限制 (單位：MB)
  public_path: null          # 指定圖片鏈接基礎路徑 (默認為 "/static/images/")
  # 使用 upgit 將圖片上傳到 GitHub 或圖床 (https://github.com/pluveto/upgit)
  upgit:
    enabled: false  # 啟用 upgit
    exec: "./upgit -c <upgit配置文件路徑> -t /artalk-img"
    del_local: true # 上傳後刪除本地的圖片

# 管理員多元推送
admin_notify:
  # 通知模版
  notify_tpl: "default"
  noise_mode: false
  # 郵件通知管理員
  email:
    enabled: true # 當使用其他推送方式時，可以關閉管理員郵件通知
    mail_subject: "[{{site_name}}] 您的文章「{{page_title}}」有新回覆"
  # Telegram
  telegram:
    enabled: false
    api_token: ""
    receivers:
      - 7777777
  # Bark
  bark:
    enabled: false
    server: "http://day.app/xxxxxxx/"
  # 飛書
  lark:
    enabled: false
    webhook_url: ""
  # WebHook
  webhook:
    enabled: false
    url: ""
  # 另支持 釘釘、Slack、LINE 等多種推送方式
  # 詳情參考：https://artalk.js.org/guide/backend/notify.html
```
