### ISSUE TITLE
【bug】关于侧边栏baseUrl与评论区baseUrl不一致

### ISSUE THREAD

**Issue by kkfive** [ArtalkJS/Artalk#283]
我的配置：
```yaml
artalk:
  server: https://api.antmoe.com/artalk/
  site: 小康博客
  visitor: true
  option:
    useBackendConf: true,
    placeholder: 评论需要留下您的昵称和邮箱哦！
    emoticons: 'https://unpkg.com/static-butterfly/public/artalk.json'
```

但是这样的的API地址sidebar好像不能正常使用。

<img width="839" alt="image" src="https://user-images.githubusercontent.com/82026204/193576829-59851006-e190-4d32-bda3-bb4808f48b47.png">
<img width="825" alt="image" src="https://user-images.githubusercontent.com/82026204/193576999-6ccae7f5-6ff8-4045-a45f-a25a741a7100.png">
