### ISSUE TITLE
图片上传功能关闭时评论框内仍然显示图片按钮

### ISSUE THREAD

**Issue by whoisxiucai** [ArtalkJS/Artalk#313]

**Comment by eryajf** [comment]
+1，也遇到了这样的情况

**Comment by whoistiger** [comment]
> +1，也遇到了这样的情况

暂时可以先用css隐藏
```css
.atk-plug-btn:nth-child(2){
    display:none !important;
}
```
