### ISSUE TITLE
评论区代码块儿渲染没有滚动也没有换行

### ISSUE THREAD

**Issue by eryajf** [ArtalkJS/Artalk#465]
如下图所示：

<img width="641" alt="image" src="https://user-images.githubusercontent.com/33259379/226162182-f4bb6d1c-b981-4467-897a-3123c29e7ee2.png">

实际上在COM后边还有内容，但是这里被截断了，代码块儿无法左右滚动，也没有换行显示。

请问下这里是博客评论插件的因素，还是后端artalk的因素呢。

我在官方评论区做了测试，发现较长之后，会自动换行，效果如下：

<img width="579" alt="image" src="https://user-images.githubusercontent.com/33259379/226162245-94a886db-302c-4224-95c4-58650555485f.png">

感觉上大概是跟插件有关。

**Comment by qwqcode** [comment]
能发一下出现问题页面的链接吗

**Comment by eryajf** [comment]
https://wiki.eryajf.net/pages/fa2478/  这里的最新评论的最后一条评论

**Comment by qwqcode** [comment]
你的主题 CSS 覆盖了 Artalk 评论代码区域的一个样式属性，可尝试添加 CSS：

```css
.artalk pre code, .atk-layer-wrap pre code {
  white-space: pre-wrap !important;
}
```
