### ISSUE TITLE
禁用图片上传和显示ip未生效

### ISSUE THREAD

**Issue by ysicing** [ArtalkJS/Artalk#476]
```yaml
img_upload:
  # Enable image upload
  enabled: false
ip_region:
  enabled: true
  db_path: "/data/ip2region.xdb"
  precision: "province"
```

但是测试发现，只有我自己的ip显示了，其他人评论待审核时显示，审核通过就不显示了。另外禁用了图片上传，好像有图片上传功能

https://ysicing.me/tools/artalk/#atk-comment-17
