### ISSUE TITLE
邮件通知不生效

### ISSUE THREAD

**Issue by Ice-Hazymoon** [ArtalkJS/Artalk#69]
配置文件：

```yml
# 邮件通知
email:
  enabled: true # 总开关
  send_type: "smtp" # 发送方式 [smtp, ali_dm, sendmail]
  send_name: '{{reply_nick}}' # 发信人昵称
  send_addr: "no-reply@xxxxx.com" # 发信人地址
  mail_subject: "[{{site_name}}] 您收到了来自 @{{reply_nick}} 的回复"
  mail_subject_to_admin: '[{{site_name}}] 您的文章 "{{page_title}}" 有新回复'
  mail_tpl: "default" # 邮件模板文件
  smtp:
    host: "smtpdm.aliyun.com"
    port: 465
    username: "no-reply@xxxxx.com"
    password: "xxxxx"
  ali_dm: # https://help.aliyun.com/document_detail/29444.html
    access_key_id: "" # 阿里云颁发给用户的访问服务所用的密钥 ID
    access_key_secret: "" # 用于加密的密钥
    account_name: "example@example.com" # 管理控制台中配置的发信地址
```

回复评论，且回复评论被审核后未收到邮件通知，已开启评论审核和 akismet 反垃圾
