### ISSUE TITLE
Ask about setup Artalk with redis cache

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#705]
I want to test a bit of redis cache configuration on Artalk, specifically my docker configuration is as follows
```
version: "3.5"
services:
  artalk:
    restart: unless-stopped
    container_name: artalk
    image: artalk/artalk-go
    ports:
      - 8181:23366
    volumes:
      - ./data:/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    expose:
      - "6379"
```
Configuration inside Artalk
![Vxg9Torhhp](https://github.com/ArtalkJS/Artalk/assets/119997727/199feeca-2361-4d17-842a-a00740f5875c)

Next, restart docker
![Ar9fCSX0Hr](https://github.com/ArtalkJS/Artalk/assets/119997727/1bfc58e8-7ee8-48f9-82be-cf63d2592c9d)

According to the notification that appears, everything seems to work normally
[
![iW3LkQMaO9](https://github.com/ArtalkJS/Artalk/assets/119997727/e7053418-f32b-44cc-a5b2-bf4a8c57e408)
](url)
On the default builtin cache I see that it uses a lot of RAM, mostly 300-400MB, on redis, it uses very little, only 4-5MB

Is this parameter correct, or have I configured it wrong?
