### ISSUE TITLE
如何关闭「此时无声胜有声」

### ISSUE THREAD

**Issue by toyo2333** [ArtalkJS/Artalk#778]
有开关关掉这个么，不想显示这个。难道是到设置里区填“空格”？，。。。

**Comment by qwqcode** [comment]
<img width="415" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/3cbf2d1c-5148-470d-88d8-82280b6bff8b">

**Comment by qwqcode** [comment]
你填空格试试呗，空格不行填 `&nbsp;`

实在不行加个 css 代码：

```css
.atk-list-no-comment { display: none; }
```
