### ISSUE TITLE
V2.8.7设置中文失败

### ISSUE THREAD

**Issue by Einstein-schrodinger** [ArtalkJS/Artalk#933]
设置中文失败
报错：{"level":"WARN","ts":"2024-06-21T10:05:34.710+0800","caller":"[i18n/i18n.go:20]","msg":"invalid locale config please check, now it is set to `en`"}

**Comment by qwqcode** [comment]
你有设置环境变量 `ATK_LOCALE` 吗，当前你的的语言配置是什么

**Comment by Einstein-schrodinger** [comment]
> 你有设置环境变量 `ATK_LOCALE` 吗，当前你的的语言配置是什么，注意是 `zh-CN`，不是下划线

docker compose 部署的，但是后台还是显示'en'，设置了之后也不生效
```yaml
version: '3.8'
services:
  artalk:
    container_name: artalk
    image: artalk/artalk-go
    restart: unless-stopped
    ports:
      - 23366:23366
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - ATK_LOCALE="zh-CN"
      - ATK_SITE_DEFAULT="Artalk评论"
```
