### ISSUE TITLE
环境变量配置后，网页后台仍然是配置文件中的数据而不是环境变量

### ISSUE THREAD

**Issue by gxres042** [ArtalkJS/Artalk#946]
## 问题描述

昨日我将我的 Artalk 实例的数据库从 SQLite 迁移至 PostgreSQL。我在 Docker Compose 模板文件指定了下述环境变量：

- `ATK_DB_TYPE`: `pgsql`
- `ATK_DB_HOST`
- `ATK_DB_USER`
- `ATK_DB_PASSWORD`
- `ATK_DB_NAME`
- `ATK_DB_PORT`

在部署成功后，Artalk 确实使用了我指定的 PostgreSQL 数据库。但是，在控制中心的「数据库」一栏却显示我正在使用 SQLite 数据库。

## 复现步骤

理论该问题可以直接复现。

第一步，通过 Docker Compose 模板文件部署 Artalk：

```
version: '3.8'
services:
  artalk:
    container_name: artalk
    image: artalk/artalk-go
    restart: unless-stopped
    ports:
      - 8080:23366
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - ATK_LOCALE=zh-CN
      - ATK_DB_TYPE=pgsql
      - ATK_DB_HOST=postgresql // 由于 Artalk 容器和 PostgreSQL 容器在同一个子网下，故 HOST 为 PostgreSQL 容器名
      - ATK_DB_USER=admin // 个人指定的 PostgreSQL 数据库用户名
      - ATK_DB_PASSWORD={password}
      - ATK_DB_NAME=artalk // 个人手动在 PostgreSQL 数据库创建的表
      - ATK_DB_PORT=5432
```

第二步，等待 Artalk 部署完成、其容器日志并无异常，打开控制中心查看「数据库」一栏是否仍是 SQLite。

> 我通过 DBeaver Community 给这个 PostgreSQL 容器创建了一个新表，随后在 Artalk 部署完成后使用该工具连上 PostgreSQL 数据库、检查 Artalk 是否正常生成了数据，最后再检查映射的 `./data` 是否创建了 SQLite 数据库文件。

## 影响到的其它方面

在上述复现的 Docker Compose 配置文件里，我同时指定了 `ATK_LOCALE`。部署完成后，界面语言确实更换成了中文，但控制面板的语言选项仍旧是 en。
